#+OPTIONS: H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc
#+STARTUP: SHOWALL INDENT
#+STARTUP: HIDESTARS
#+BEGIN_HTML
---
---
layout: post
title: Яблочная клавиатура
---
#+END_HTML

Долгие годы верой и правдой служила мне безымянная китайская
клавиатура. Не сказать, что она меня подвела — сих пор в
идеальном состоянии. Но проходят времена, сменяются эпохи. И вот, со
сменой очередной компьютерной эпохи пришла пора сменить
клавиатуру. Старый компьютер, вернее, алюминиевый скелет оного, я
отнёс на помойку и купил новый черный «кубик» *ASRock ION 330* на
двуядерном атоме и чипсете NVidia ION — почти идеальное решение для
бесхитростного домашнего компьютера.

Всё бы ничего, да вот беда: старую клавиатуру и мышь некуда воткнуть
--- на нынешних компьютерах нет интерфейса PS/2. На эту проблему я
купил переходник-разветвитель типа «два PS/2 в один USB». Как
говорится, поменял шило на мыло. Мышь работала исправно. Иной раз,
правда, не определялась после загрузки. Клавиатура тоже работала
исправно. Но случилось нечто неведомое с обработкой удержания клавиш,
что приводило к невозможности нормально поиграть в шутеры и
отредактировать текст в эмаксе, потому как у меня Caps Lock с
Control'ом поменяны местами и при удержании Caps Lock'а он «срывался».

Делать нечего, пришлось купить клавиатуру. На первое время взял
более-менее вменяемую клавиатуру A4 с «косыми»
клавишами. Попользовался с недельку, покуда не решил купить таки
нормальную.

Над выбором нормальной клавиатуры долго думать не пришлось. Потому что
я еще ни разу в своей жизни в глаза не видел нормальной клавиатуры
(ну, кроме той старой китайской). Всё что продается в местных
магазинах --- мусор в широком ценовом диапазоне. Последняя надежда
оставалась на интернет-магазины. Залез в интернеты, поскреб по сайтам,
в итоге остановился на двух клавиатурах. Маленькой проводной
клавиатуре Apple. И клавиатуре Happy Hacking.

Happy Hacking --- это воплощение мечты эмаксера. Клавиши с глубоким
ходом, ничего лишнего --- всё на своих местах. Но дороговато. Продаётся
только на амазоне. Так что с доставкой выходит очень приличная сумма.

Я уже давно присматриваюсь к продукции фирмы Apple, поэтому решил
взять яблочную клаву. При заказе я выбрал доставку EMS. Стоит она
довольно дорого --- 700 рублей для доставки коробки весом меньше
килограмма из Москвы в пригород Уссурийска (это на другом конце
страны). Но оперативность меня ну очень порадовала --- через 4 дня ко
мне домой курьер занёс белую коробочку с яблоком.

Немного удивился, обнаружив в коробке немного не то, что представлено
на картинке на официальном сайте. Клавиша Enter не маленькая и
продолговатая, как Shift, а «уголком».

С клавиатурой Apple в Ubuntu Эмакс работает нормально. Сама клавиатура
тоненькая и тяжелая. Даже мультимедиа клавиши для управления звуком и
открытия привода работают. Отлично.  Печатать удобно, но клавиши
стрелок такие маленькие, да и PgUp/PgDn нет, вынуждает «правильно»
пользоваться Эмаксом: сочетания C-v, M-v, C-d, C-w, C-n, C-p, C-f,
C-b используются повсеместно.

В отличие от стандартных виндовых клавиатур, на яблочной нет клавиши
Windows (еще бы на их клавиатуре был логотип конкурента), вместо
неё --- клавиша Alt, а на месте Alt --- клавиша Command. Опять таки,
малый размер и неудобное положение вызывают неудобство, но оно
решается перестановкой Alt и Cmd в Эмаксе:

#+BEGIN_SRC EMACS-LISP
(setq x-meta-keysym 'super)
(setq x-super-keysym 'meta)
#+END_SRC

Определенно, я понимаю любителей Apple, и даже сам становлюсь
таковым. До этого я и не думал, что клавиатуры могут быть /такими/.
