#+OPTIONS: H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc
#+STARTUP: SHOWALL INDENT
#+STARTUP: HIDESTARS
#+BEGIN_HTML
---
---
layout: post
title: Emacs 23 в Ubuntu
---
#+END_HTML

Недавно вышел Emacs 23.2, в главных фичах которого --- поддержка
шрифтовых настроек гнома, то есть шрифты в нём /такие же/, как и во
всех остальных программах. Одного этого достаточно, чтобы не
задавая лишних вопросов, на него перейти. Но это при условии, что
пользуетесь эмаксом в иксах со сглаженными шрифтами.

К слову, в предыдущей версии нормального отображения шрифтов можно
было добиться только путем выпиливания кучи всякого из =/etc/fonts.d=.

Конечно же, как только эмакс вышел --- мне сразу захотелось поставить
свежую версию, но я не нашел на просторах сети ни одного репозитория с
23.2. Дебиановские не в счёт --- в Lucid Lynx с ними некоторые проблемы.
Пришлось собирать. Рецепт по сборке нашел на эмаксовой вики. Приведу
его здесь.

Устанавливаем необходимые для самостоятельной сборки программы:

: sudo aptitude install build-essential libxpm-dev libgif-dev libtiff-dev libjpeg-dev libgtk2.0-dev libdbus-1-dev texinfo

Качаем исходники:

: wget http://ftp.gnu.org/gnu/emacs/emacs-23.2.tar.bz2
  
Распаковываем архив, и в директории с исходниками выполняем:

: sudo ./configure --with-x-toolkit=gtk --with-xft --prefix=/home/haru/Apps
: sudo make
: make install

Не то чтоб процесс был черезчур сложен --- это скорее заметка для себя
на будущее.
