#+OPTIONS: H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc
#+STARTUP: SHOWALL INDENT
#+STARTUP: HIDESTARS
#+BEGIN_HTML
---
layout: post
title: SICP для Emacs
---
#+END_HTML

Не просите меня, милостивый государь, рассказать вам что есть такое
«SICP» — мне неудобно, право слово. Смущаюсь я, да и к чему оно: коли
вы лиспер, так и сами знаете лучше моего, а ежели нет — то я вам так
скажу: книга сия есть священное писание для всякого православного
программиста; иметь электрический или бумажный экземпляр этой великой
книги в своей программерской библиотеке — не просто честь, как
например, иметь томик «Искусства программирования» при том что его
никто не читает; «Структура и интерпретация компьютерных программ» —
это в высшей степени насущная вещь и требует досконального изучения —
в нашу-то эпоху динамических языков.

Мне, как приверженцу церкви Эмакса, дóлжно рассказать вам о
специальном, церковном издании книги в формате /info/ — для простого
и оперативного доступа прямо из справки по =M-x info=. Этим все сказано.

#+begin_html
<div class="figure">
<pre>
                           .,ad88888888baa,
                  _    ,d8P"""        ""9888ba.      _
                 /  .a8"          ,ad88888888888a   |\
               /   aP'          ,88888888888888888a   \
              /  ,8"           ,88888888888888888888,  \
             |  ,8'            (888888888888888888888, |
            /  ,8'             `8888888888888888888888  \
            |  8)               `888888888888888888888, |
Procedure,  |  8                  "88888 Apply 8888888) | Expression
Arguments   |  8     Eval          `888888888888888888) | Environment
            |  8)                    "8888888888888888  |
            \  (b                     "88888888888888'  /
             | `8,                     8888888888888)  |
             \  "8a                   ,888888888888)  /
              \   V8,                 d88888888888"  /
              _\| `8b,             ,d8888888888P' _/
                     `V8a,       ,ad8888888888P'
                        ""88888888888888888P"
                             """"""""""""
</pre>
<p> Псевдографика из книги иллюстрирует природу языков программирования.</p>
</div>
#+end_html

Кидаем директорию [[http://db.tt/IuKamtg][info]] в директорию =.emacs.d= и дописываем в
настройки пару строчек

#+begin_src emacs-lisp
(require 'info)
(add-to-list 'Info-directory-list "/home/haru/.emacs.d/info")
#+end_src
