#+OPTIONS: H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc
#+STARTUP: SHOWALL INDENT
#+STARTUP: HIDESTARS
#+BEGIN_HTML
---
layout: post
title: Книга «Бог как иллюзия»
---
#+END_HTML

Продолжаю читать Ричарда Докинза, на этот раз замечательную книгу «Бог
как иллюзия». Не перестаю поражаться чудовищным примерам религиозной
темноты, мракобесия и связанного с этим насилия всех форм и оттенков.

С моей колокольни довольно трудно принимать всерьез весь этот
религиозный ужас, продолжающий охватывать человечество на протяжении
многих тысячелетий — с глубокой древности и по наши дни. Благо мое
окружение с самого детства было довольно атеистическим, если не
считать остаточных наполовину православных, наполовину анимических, в
духе русского народного вуду с бабками-целительницами и сглазами,
осколков «веры» моей матери; и в свое время временно подверженной
телевизионной водозаряжательной заразе Чумака, а ныне заразе
умеренного православия, бабушки. В целом, я рад за себя; рад, что
благодаря скептицизму и любви к естественным наукам, а может,
благодаря недостаточно активному промыванию мозга, с раннего детства
мне удалось избежать поражения моего разума всем этим религиозным
дерьмом.

Что же до книги — автор разносит религию во всех её проявлениях и по
всем фронтам, так что после вдумчивого чтения, если у человека
осталось хоть сколько-то живое мышление, не должно остаться сомнений
насчет истинной природы религии и вызываемой ею веры.
