#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:nil skip:nil d:t tags:not-in-toc

* Что имеем

Писать на Java вообще и на Java для Google App Engine в
частности---занятие далекое от интуитивных представлений о приятном
программировании. Разработчика ожидают мегатонны штампованного кода (в
этом вся Java) и долгий (невыносимо долгий для человека, развращенного
REPL) цикл разработки Edit-Compile-Run с постоянными перезапусками
локального веб-сервера. Clojure избавляет программиста от этих
недостатков---он получает возможность постепенно отлаживать своё
веб-приложение в одной сессии, без перезапуска локального сервера
разработки, и писать лаконичный код на языке предметной области, а не
копипастить непотребство.

За две недели, прошедшие с последней публикации чуда не
случилось. Инфраструктура для разработки не появилась как по мановению
волшебной палочки, поэтому чтобы продолжить свое повествование мне
пришлось самому сесть за штудирование GAE SDK и кусочков кода,
разбросанных по десятку ресурсов и написать добрую пару сотен строчек
кода. Мои старания увенчались успехом и я явил свету маленькую, но
практичную библиотеку для запуска локального веб-сервера GAE с
поддержкой авторизации (авторизация была большой загвоздкой).

Сам я веб-программировании---не в зуб ногой. Никакого опыта. Поэтому
осваиваться буду в процессе написания своего маленького
веб-приложения.

* Что надо

Среднестатистический современный лиспер использует инструмент по
последней моде ранних 80-ых. Читателю сего блога, желающего
проследовать моим путем создания веб-приложения понадобятся следующие
программы:
- Emacs :: За неимением лучшего послужит интегрированной средой
           разработки на лиспе. Желательно ознакомиться с моими
           статьями "Настройка Emacs для программирования на Clojure"
           и "Emacs Starter Kit" перед началом использования.
- Консоль :: Разумеется консоль в UNIX---Mac OS X или Linux. Под
             Windows воспользоваться инструментарием будет тяжеловато.
- Chrome/Firefox/Safari :: Мы пишем веб-приложение, без браузера тут
     делать нечего.
- [[http://github.com/technomancy/leiningen][Leiningen]] :: Пакетный менеджер для Clojure, средство сборки и
               тестирования проекта.
- GIT :: Система контроля версий, которой я пользуюсь. Разрабатывать
         даже небольшое приложение без контроля версий---гиблое
         дело. Код приложения я опубликую на гитхабе.
- [[http://code.google.com/appengine/downloads.html#Google_App_Engine_SDK_for_Java][Google App Engine Java SDK]] :: Пакет jar'ов от Google: библиотеки для
     онлайновой и оффлайновой разработки, скрипты для запуска
     приложения на локальном сервере и для заливки собранного
     приложения на Google App Engine. Скачать SDK нужно обязательно,
     но особо заморачиваться не стоит: все необходимые jar'ы обеспечит
     leiningen, SDK нужен лишь ради скриптов для заливки.
- Google App Engine Python SDK :: Не лишним, хотя и не обязательным
     будет скачать SDK питона---в нем есть несколько фич, которых нет
     в Java SDK, потому как поддержка последнего появилась у гугла
     позже.
- Google Account :: Нужна регистрация на гугле, без этого---никак. Вы
                    же используете GMail?

* Как идет работа

Работа над веб-приложением от создания и до запуска в облаке
организована следующим образом:

1. Создание приложения.
2. Запуск лисп-машины (ой, простите, джава-машины :) и локального
   GAE-сервера в ней. Интерактивная разработка в лучших
   традициях---каждое внесенное в код изменение обретает силу здесь и
   сейчас. Никаких перекомпиляций и перезапусков.
3. Компиляция отлаженного приложения и размещение оного в облаке.

* Создание приложения

** Там

На облачной стороне элементарно---все происходит в один шаг, и
заострять на этом внимание не стоит: нужно войти под Google-аккаунтом
на [[https://appengine.google.com/][App Engine]] и зарегестрироваться через SMS; выбрать имя приложения и
щелкнуть кнопочку создать.

** Здесь

Веб-приложение создается на компьютере программиста, а это чуточку
сложнее чем просто ткнуть пару кнопок. Приложение представляет собой
набор файлов: скомпилированных, статических, настроечных и
библиотечных, оно организовано в файловую структуру, называемую
WAR---Web Application Archive.

#+BEGIN_EXAMPLE
project.clj
README
src
test
war
  resources
    css
      stylesheet.css
    img
      favicon.png
  WEB-INF
    classes
    lib
    appengine-web.xml
    web.xml
#+END_EXAMPLE





 Всё что находится в директории war
будет загружено на сервер. Отдельно идут исходники в директории, они на сервер не
загружаются.

---статических (CSS страницы, JavaScript, картинки и
прочее), настроек (имя приложения,

An app can also include static files, such as images, CSS stylesheets, and browser
JavaScript. App Engine serves these files directly to clients in response to requests for
corresponding URLs without invoking any code. The app’s configuration specifies
which of its files are static, and which URLs to use for those files.
The application configuration includes metadata about the app, such as its application
ID and version number. When you deploy the app to App Engine, all of the app’s files,
including the code, configuration files, and static files, are uploaded and associated
with the application ID and version number mentioned in the configuration. An app
can also have configuration files specific to the services, such as for datastore indexes,
task queues, and scheduled tasks. These files are associated with the app in general,
not a specific version of the app.

~/Sources ~/Applications/lein new dv-chan


* Шаблон проекта

Веб-приложение для JVM и Google App Engine имеет следующую структуру:
